### ISSUE TITLE
We need the UI

### ISSUE THREAD

**Issue by iammerus** [flux-player/flux-app#1]
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!
We want the UI!

Thank you

**Comment by spaghettiwews** [comment]
This is just noise. Please desist from such behaviour and tone on OSS projects. No one owes you anything 😊

**Comment by iammerus** [comment]
@spaghettiwews You are rude and this project is going to fail because of people like you. Mxm!

**Comment by spaghettiwews** [comment]
Typical entitled Gen Z'er. I want I want I want. Some of us have lives. I'll get to it. When. I. Get. To. It.

**Comment by iammerus** [comment]
Okay boomer 😒
